server.port=8084

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web.context.request.async=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.org.apache.catalina=DEBUG
