server.port=8084

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web.context.request.async=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.org.apache.catalina=DEBUG

spring.datasource.url=jdbc:h2:mem:fridgedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Die Speicherdatenbank bei jedem Start mit der schema.sql Datei initialisieren
spring.sql.init.mode=always
