server.port=8082

# Datenbank konfigurieren
spring.datasource.url=jdbc:sqlite::resource:cocktails.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialekt konfigurieren
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# SQL protokollieren
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
